name: Disable Default Pages Workflow

on:
  workflow_dispatch:

jobs:
  disable-default:
    runs-on: ubuntu-latest
    steps:
      - name: Disable Default Pages Workflow
        run: |
          curl -X PUT \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/pages-build-deployment.yml/disable" 